name: Publish Docker

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        step:
            - uses: actions/checkout@master
            - name: Publish to registry
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  registry: docker.pkg.github.com
                  name: docker.pkg.github.com/nikolay1717/nest-api-demo/nest-api-demo
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKERPASSWORD }}
                  tags: 'develop'
